
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pote2 = 7;
  public static final int pote1 = 6;
  public static final int EOF = 0;
  public static final int menos = 3;
  public static final int multi = 5;
  public static final int letra = 9;
  public static final int numero = 8;
  public static final int division = 4;
  public static final int error = 1;
  public static final int mas = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "division",
  "multi",
  "pote1",
  "pote2",
  "numero",
  "letra"
  };
}

